### ISSUE TITLE
Bug in collapse/uncollapse buttons

### ISSUE THREAD

**Issue by stothe2** [brain-score/brain-score.web#22]
Collapse/uncollapse buttons don't work when the website is first accessed using [brain-score.org](brain-score.org) URL. However, they work if you click on [brain-score.org#leaderboard](brain-score.org#leaderboard), and also, if you now go back from the `leaderboard` section _back_ to [brain-score.org](brain-score.org). It also works if you directly access [brain-score.org#leaderboard](brain-score.org#leaderboard).

Browser: Firefox 79.0

**Comment by mschrimpf** [comment]
I'm pretty sure this is because [`table-expansions.js`](https://github.com/brain-score/brain-score.web/blob/305cd47d4bff40ab8bba8617692f7ab9f3a09b86/benchmarks/templates/benchmarks/base.html#L52) is loaded before the html renders, thereby not finding any [`clicker`](https://github.com/brain-score/brain-score.web/blob/305cd47d4bff40ab8bba8617692f7ab9f3a09b86/static/benchmarks/js/table-expansion.js#L3) elements. 
Fix by putting inside
`$(document).ready(function () { ... }`
